### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by andrewstevenson**
Thanks for forking, can we expect a PR? But I've removed to webhook from travis to our slack channel

### CODE REVIEW

**Comment by eriknaslund** [comment]
@andrewstevenson Removed the slack notifications in commit https://github.com/eKIK/stream-reactor/commit/cdca3513f79fdbc237ec29928e7f4c0348173586. The S3 credentials are going to be very short-lived and it's fine for them to be here for now.

Right now I'm just trying to get things to build properly. Had huge issues getting it to work locally, so I resorted to Travis where things are working a bit better at least.

You can expect 2 pull requests later on. At that point in time I'll make sure to do them from a clean repo without a lot of messed up history though :)

**Comment by andrewstevenson** [comment]
what issues did you have?

**Comment by andrewstevenson** [comment]
there's some know issues with guava, especially when using elastic and hbase.
http://docs.datamountaineer.com/en/latest/faq.html
explicitly setting the jars first in the classpath usually sorts it.

#For Elastic
#export CLASSPATH=kafka-connect-elastic-0.2.3-3.0.1.jar

#For HBASE
#export CLASSPATH=kafka-connect-hbase-0.2.3-3.0.1.jar

**Comment by eriknaslund** [comment]
Ah yeah, I had the Guava issue but I actually just needed to build the .jar for HBase, so I did the brute-force approach of removing everything else from settings.gradle. Didn't think of the CLASSPATH trick. As you might guess, I'm not really a Java developer, just when I have to :).

I don't have the stacktraces any more, but I'll be happy to reproduce it afterwards when I'm done and post them here.

**Comment by eriknaslund** [comment]
@andrewstevenson 
So, I managed to reproduce a couple of things, and eventually even get a complete setup script for a build that works for me.

I noticed that you were using Ubuntu 12.04 on Travis, so that's what I used to get my build working. The script to install all requirements and get a successful build is attached here: 
[setup.txt](https://github.com/eKIK/stream-reactor/files/1035815/setup.txt)

Trying to run gradlew fatJar on Ubuntu 17.04 errors out almost immediately, see attached error log here: 
[out-1704.txt](https://github.com/eKIK/stream-reactor/files/1035818/out-1704.txt)

On 14.04 things work a bit better, but builds still fail when compiling. This wasn't on a completely clean environment though, openjdk and scala was installed before etc. I've attaching both info and debug to make it a bit easier to filter: 
[out-1404-info.txt](https://github.com/eKIK/stream-reactor/files/1035821/out-1404-info.txt) 
[out-1404-debug.txt](https://github.com/eKIK/stream-reactor/files/1035823/out-1404-debug.txt)

Let me know if you want me to open a github issue or something. Perhaps it would make sense to include my setup.txt script somewhere in the README.md to make it easier for people to get started? Doing so using that script and a Vagrant box is rather simple.

All the best!

**Comment by andrewstevenson** [comment]
Which gradle version? You need gradle 3
________________________________

**Comment by eriknaslund** [comment]
I used gradlew and from what I understood it should download the correct version of gradle automatically. If  that's not the case the system-wide installed gradle is version 3.5.

**Comment by eriknaslund** [comment]
Sorry, I confused myself. It's just the building of kafka-connect-query-language that works using the setup.txt script. I still can't manage to build stream-reactor, the errors in out-1404-*.txt still appear. Any advice would be greatly appreciated :).

**Pull request closed without merging**
